import { ROLES, GOALS, INDUSTRIES } from '../src/constants.js';
const rows = [
['Maya Chen',0,[0,1],[1,0],'A technical co-founder to build the next generation of AI productivity tools.','Early-stage fundraising insights and a fresh perspective on your pitch.','MBA ’26 · Co-founder, Capsule','MC','#e8dfd4',0,'Previously a product manager at Notion. Building AI tools for small teams.'],
['Alex Rivera',3,[1,0],[4,1],'An early-stage team building something meaningful in climate or AI.','Full-stack development, rapid prototyping, and turning ideas into an MVP.','MEng ’26 · Full-stack engineer','AR','#d9e6df',1,'Full-stack engineer with React, Python, and AI prototyping experience.'],
['Priya Sharma',1,[0,4],[0,3],'Ambitious founders rethinking how we work, learn, and live.','Pitch deck feedback, warm investor introductions, and go-to-market advice.','MBA ’25 · Associate, Westward Ventures','PS','#e8dce6',2,'Early-stage investor focused on AI and fintech. Former strategy consultant.'],
['Jordan Williams',2,[6,10],[2,1],'A co-founder passionate about making sustainable living accessible.','Customer research, business strategy, and plenty of big ideas.','MBA ’27 · Exploring climate tech','JW','#dde5d0',3,'Sustainability consultant exploring circular economy startups.'],
['Sophie Park',3,[1,5],[4,2],'Founders who need a design partner to bring their vision to life.','Product design, brand strategy, and a thoughtful eye on your user experience.','MDes ’26 · Product designer','SP','#e7ded1',4,'Product designer experienced in consumer products, Figma, and brand systems.'],
['Daniel Okafor',0,[2,0],[1,3],'Healthcare operators and an engineer to help scale our patient platform.','Healthcare industry insights and lessons from building a zero-to-one startup.','MBA ’26 · Founder, CareBridge','DO','#d9e1e8',5,'Founder building AI-powered patient navigation. Previously worked in hospital operations.'],
['Emma Thompson',1,[6,7],[0,4],'Climate and hardware founders ready to share their next big idea.','Seed-stage pitch feedback, climate investor connections, and financial modeling.','MBA ’24 · Investor, Evergreen Capital','ET','#eadfcf',6,'Seed investor in climate and deep technology with a background in engineering.'],
['Rohan Patel',3,[0,3],[1,4],'An EdTech founder looking for a hands-on technical co-founder.','Machine learning, full-stack development, and experience shipping learning tools.','EECS ’26 · ML engineer','RP','#dedcf0',7,'Machine learning engineer building personalized learning systems using Python and React.'],
['Olivia Martinez',0,[5,10],[0,3],'Mentorship on fundraising and bringing a sustainable consumer brand to market.','Consumer research, community building, and marketing strategy.','MBA ’27 · Founder, Common Goods','OM','#eadbd5',8,'Consumer brand founder focused on ethical retail and community-led growth.'],
['James Liu',2,[4,1],[2,4],'A startup internship where I can work on fintech product strategy.','Financial modeling, market analysis, and hands-on operations support.','MBA ’27 · Fintech enthusiast','JL','#dce8df',9,'Former financial analyst exploring fintech product management.'],
['Aisha Johnson',0,[3,10],[1,3],'A product designer and mentors who care about equitable education.','EdTech connections, user research, and experience building social impact ventures.','MBA ’26 · Co-founder, OpenClass','AJ','#e5dce8',10,'EdTech founder creating accessible career education. Background in nonprofit operations.'],
['Ben Cooper',4,[8,9],[5,2],'Creative people exploring what is next for cities and local communities.','Storytelling, event photography, and introductions across the Bay Area.','Berkeley alum · Community builder','BC','#dce5eb',11,'Community organizer and storyteller with experience in real estate and media.']
];
export const seed = rows.map(([name,role,industries,goals,lookingFor,canOffer,headline,initials,color,i,linkedInSummary])=>({id:`hea-${i+1}`,name,heaMember:i%4===3?'No':'Yes',role:ROLES[role],linkedIn:`https://www.linkedin.com/in/${name.toLowerCase().replaceAll(' ','-')}-hea-demo`,connectGoals:goals.map(x=>GOALS[x]),lookingFor,canOffer,industries:industries.map(x=>INDUSTRIES[x]),attendance:i%4===2?'zoom':'in-person',headline,initials,color,linkedInSummary}));
